---
title: Bias in pre-post designs -- An example from the Turnbaugh et al (2006) mouse
  fecal transplant study
author: Jeff Walker
date: '2018-03-06'
slug: bias-in-pre-post-designs-an-example-from-the-turnbaugh-et-al-2006-mouse-fecal-transplant-study
categories: []
tags:
  - ancova
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(Hmisc)
library(ggplot2)
library(mvtnorm)
library(data.table)
#library(lme4)
#library(lmerTest)

gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}

```
# Summary
This post is motivated by a twitter link to a [recent blog post](https://honey-guide.com/2018/02/13/graphic-faecal-transplants-and-obesity/) critical of the old but influential study [An obesity-associated gut microbiome with increased capacity for energy harvest](https://scholar.google.co.uk/scholar?hl=en&as_sdt=0%2C5&q=An+obesity-associated+gut+microbiome+with+increased+capacity+for+energy+harvest.&btnG=) with [impressive citation metrics](https://www.nature.com/articles/nature05414/metrics). In the post, Matthew Dalby smartly used the available data to reconstruct the final weights of the two groups. He showed these final weights were nearly the same, which is not good evidence for a treamtment effect, given that the treatment was randomized among groups.

This is true, but doesn't quite capture the essence of the major problem with the analysis: a simple t-test of differences in percent weight change fails to condition on initial weight. And, in pre-post designs, groups with smaller initial measures are expected to have more change due to [regression to the mean](https://en.wikipedia.org/wiki/Regression_toward_the_mean). This is exactly what was observed. In the fecal transplant study, the initial mean weight of the rats infected with *ob/ob* feces was smaller (by 1.2SD) than that of the rats infected with *+/+* feces and, consequently, the expected difference in the change in weight is not zero but positive (this is the expected difference *conditional on an inital difference*). That is, unless the treatment effect is estimated conditional on (or ``adjusted for'') the initial weight, the estimate is biased, except under very limited conditions explained below.

Regression to the mean also has consequences on the hypothesis testing approach taken by the authors. Somewhat perplexingly, a simple $t$-test of the post-treatment weights or of pre-post difference in weight, or of percent change in weight does not have elevated Type I error. This is demonstrated using simulation below. The explaination is, in short, the Type I error rate is also a function of the initial difference in weight. If the initial difference is near zero, the Type I error is much less than the nominal alpha (say, 0.05). But as the intial difference moves away from zero, the Type I error is much greater than the nominal alpha. Over the space of the initial difference, these rates average to the nominal alpha.

# The original results
Turnbaugh et al. showed that mice with feces from obese (*ob/ob*) donors had higher weight gain than mice with feces from lean (*+/+*) donors, presumably because of the differences in microbial communities between the donor types (shown elsewhere in their paper). To support the inference of a large difference in weight change, they illustrated the percent change in each treatment level in their Fig 3C, which I replicate using simulated data generated to match their summary statistics (the original data are not available). Turnbaugh et al. used a simple t-test of the percent change scores (there is also correlated error or clustering due to two donors and 4-5 recipients per donor, but I ignore this and assume independence).

In a randomized experiment with a pre-treatment measure $X$ and a post-treatment measure $Y$, an unbiased estimate of the treatment effect $\tau$ is found by modeling the post-treatment measure using the ANCOVA-like linear model
$$Y = \alpha + \beta X + \tau T$$
where $T$ is a dummy variable indicating treatment assignment with $T=0$ assigned to the control group and $T=1$ to the treated group. If the pre-treatment and post-treatment variance is the same, then $\beta$ is the correlation between initial and final measures.
