---
title: What is an R doodle?
author: Jeff Walker
date: '2018-03-07'
slug: what-is-an-r-doodle
categories: []
tags: []
---

An R doodle is a short script to check intuition or understanding. Almost always, this involves generating fake data. I might create an R doodle when I'm reviewing a manuscript or reading a published paper and I want to check if their statistical analysis is doing what the authors think it is doing. Or maybe I create it to help me figure out what the authors are doing. Or I might be teaching some method and I create an R doodle to help me understand how the method behaves given different input (fake) data sets. Or I might create an R doodle to help others understand - this could be for students, or some blog comment, or my department colleagues.

## Why this blog?
My R doodles are reactionary - I read something and start coding in R studio. I have an organized folder of these on my Google drive. Some I have expanded into published papers ([here](http://onlinelibrary.wiley.com/doi/10.1111/evo.12406/full), [here](http://jeb.biologists.org/content/218/22/3647.eLetters), and [here](https://peerj.com/articles/2575/)) but I have a file drawer full of effectively completed manuscripts that are unlikely to be submitted. Writing R doodles, and especially the manuscripts, consumes a large fraction of my professional time, but others don't really gain from this hard work unless I publish the results. This blog was started to archive my R doodles going forward. Some of these will be expanded into longer scripts and posts. Some of these will be fleshed out into manuscripts for archiving at [PeerJ preprints](https://peerj.com/preprints/) or bioR$\chi$iv(https://www.biorxiv.org). Others will be expanded into [Shiny apps](https://shiny.rstudio.com/gallery/). Some I might even submit for publication in a journal. But ultimately, the goal is to have an archive for teaching and learning. 

## Motivators.
Three blogs have hugely motivated my professional practice. First, [Andrew Gelman's blog](http://andrewgelman.com) has profoundly influenced how I think about statistical analysis. Equally important, the blog posts are often followed by a rich comment section. Second, Jeremy Fox, Meghan Duffy, and Brian McGill at [Dynamic Ecology](https://dynamicecology.wordpress.com) have consistently thought-provoking posts on the science of ecology and the practice of being an academic ecologist, including the path to get there. The discussion can be a rich source of ideas. Finally, Terry McGlynn at [Small Pond Science](https://smallpondscience.com) compliments the Dynamic Ecology blog with more entries devoted specifically to mentoring and teaching and advocating for the demographic of students that are most common outside of the R1 universities and elite small liberal arts colleges.

## Caveats
My statistics training was classical biostatistics -- both [Robert Sokal](https://en.wikipedia.org/wiki/Robert_R._Sokal) and [James Rohlf](http://life.bio.sunysb.edu/ee/rohlf/) were my principal mentors during my PhD years. But, I have zero training in Math, Mathematical statistics, or Computer Science and this will be evident in the way I think and write. Statisticians frequently comment on the muddled thinking found in statistics textbooks written by Biologists (or non-statisticians generally). That said, it is pretty easy to find muddled thinking in textbooks written by statisticians and even easier to find muddled thinking in biology papers with statisticians on the author list. Statistical thinking just isn't that easy.