---
title: How to estimate synergism or antagonism
author: Jeff Walker
date: '2020-11-03'
slug: how-to-estimate-synergism-or-antagonism
categories:
  - stats 101
tags:
  - anova
  - categorical X
  - interaction
  - synergism
  - antagonism
keywords:
  - tech
---

motivating source: [Integration of two herbivore-induced plant volatiles results in synergistic effects on plant defense and resistance](https://onlinelibrary.wiley.com/doi/abs/10.1111/pce.13443)

# What is synergism or antagonism?

(this post is a follow up to [What is an interaction?](https://rdoodles.rbind.io/posts-biocstyle/2020-11-03-what-is-an-interaction.html))

In the experiment for Figure 1 of the motivating source article, the researchers were explicitly interested in measuring any synergistic effects of `hac` and `indole` on the response. What is a synergistic effect? If `hac` and `indole` act independently, then the response should be **additive** -- the HAC+Indole effect should simply be the sum of the independent HAC and Indole effects. A HAC+Indole effect that is larger than the sum of the two independent effects is evidence of a synergistic (positive) interaction. A HAC+Indole effect that is less than the sum of the two independent effects is evidence of an antagonistic (negative) interaction.

Continue with [How to estimate synergism or antagonism](https://rdoodles.rbind.io/posts-biocstyle/2020-11-03-how_to_measure_synergism.html)