---
title: "Main effects in ANOVA with type III ss"
author: "Jeff Walker"
date: "11/4/2019"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(emmeans)
library(ggpubr)
library(harrellplot)
library(cowplot)
library(car)
```


```{r}
set.seed(1)
n <- 10

# get random error
sigma <- 2.4
epsilon <- rnorm(n*2*2, sd=sigma)

snail_levels <- c("low","high")
crab_levels <- c("absent","present")
fake_data <- data.table(
  snail = factor(rep(snail_levels, each=n*2),
                snail_levels),
  crab = factor(rep(rep(crab_levels, each=n), 2), crab_levels)
)
X <- model.matrix(~snail*crab, data=fake_data)
beta <- c(15, -4, -2, 2)
fake_data[, algae := (X%*%beta)[,1] + epsilon]
beta2 <- c(15, -4, -4, 2)
fake_data[, algae2 := (X%*%beta2)[,1] + epsilon]

# reorder crab factor levels for image
crab_levels <- c("absent","present")
fake_data[, crab_reorder := factor(crab, crab_levels <- c("present", "absent"))]

# simple effects
fit <- lm(algae ~ snail*crab, data=fake_data)
coef(summary(fit))
fit.emm <- emmeans(fit, specs=c("snail", "crab"))
(fit.pairs <- contrast(fit.emm,
                      method="revpairwise",
                      simple="each",
                      combine=TRUE,
                      adjust="none")
)

# this is for re-order factor levels in plot
fit <- lm(algae ~ snail*crab_reorder, data=fake_data)
coef(summary(fit))
fit.emm <- emmeans(fit, specs=c("snail", "crab_reorder"))

set.seed(1)
pd <- position_dodge(0.8)
gg_response_1 <- ggerrorplot(
  x = "snail",
  y = "algae",
  color = "crab_reorder",
  add = c("mean_ci", "jitter"),
  alpha=0.5,
  position = pd,
  palette = "jco",
  data = fake_data
) +
  #geom_point(data=fit.emm, aes(x=snail, y=emmean, fill=crab),
  #          position=pd, size=3) +
  geom_line(data=summary(fit.emm), aes(x=snail, y=emmean, group=crab_reorder),
            position=pd) +
  NULL

fit <- lm(algae2 ~ snail*crab, data=fake_data)
coef(summary(fit))
fit.emm <- emmeans(fit, specs=c("snail", "crab"))
(fit.pairs <- contrast(fit.emm,
                      method="revpairwise",
                      simple="each",
                      combine=TRUE,
                      adjust="none")
)

# this is for re-order factor levels in plot
fit <- lm(algae2 ~ snail*crab_reorder, data=fake_data)
coef(summary(fit))
fit.emm <- emmeans(fit, specs=c("snail", "crab_reorder"))

set.seed(1)
pd <- position_dodge(0.8)
gg_response_2 <- ggerrorplot(
  x = "snail",
  y = "algae2",
  color = "crab_reorder",
  add = c("mean_ci", "jitter"),
  alpha=0.5,
  position = pd,
  palette = "jco",
  data = fake_data
) +
  #geom_point(data=fit.emm, aes(x=snail, y=emmean, fill=crab),
  #          position=pd, size=3) +
  geom_line(data=summary(fit.emm), aes(x=snail, y=emmean, group=crab_reorder),
            position=pd) +
  NULL


plot_grid(gg_response_1, gg_response_2)

```

# Balanced data
```{r, message=FALSE, warning=FALSE}
m1 <- lm(algae ~ snail*crab, data=fake_data)
m2 <- lm(algae ~ snail + crab, data=fake_data)
m1_emm <- emmeans(m1, specs="snail")
m2_emm <- emmeans(m2, specs="snail")
m1_marginal <- contrast(m1_emm, method="revpairwise", adjust="none")
m2_marginal <- contrast(m2_emm, method="revpairwise", adjust="none")

con3 <- list(snail=contr.sum, crab=contr.sum)
m3 <- lm(algae ~ snail*crab, data=fake_data, contrasts=con3)
m4 <- lm(algae ~ snail + crab, data=fake_data, contrasts=con3)
m3_coef <- coef(summary(m3))
m4_coef <- coef(summary(m4))
m3_anova <- Anova(m3, type="3")
m4_anova <- Anova(m4, type="3")

(res_table <- data.table(" "=c("Estimate", "SE", "df", "statistic", "p-value"),
  marginal_full=unlist(summary(m1_marginal)[1, c(2:6)]),
  anova_full=c(NA, NA, round(m3_anova["Residuals", "Df"],0), unlist(m3_anova[2, 3:4])),
  marginal_add=unlist(summary(m2_marginal)[1, c(2:6)]),
  anova_add=c(NA, NA, round(m4_anova["Residuals", "Df"],0), unlist(m4_anova[2, 3:4])))
)

```


# Unbalanced data
```{r, message=FALSE, warning=FALSE}
set.seed(1)
inc <- c(1:10,
         sample(11:20, 6),
         sample(21:30, 8),
         sample(31:40, 5))
fake_data_missing <- fake_data[inc,]
fake_data_missing[, .(N=.N), by=c("snail", "crab")]

m0 <- lm(algae ~ snail, data=fake_data_missing)
m1 <- lm(algae ~ snail*crab, data=fake_data_missing)
m2 <- lm(algae ~ snail + crab, data=fake_data_missing)
m1_emm <- emmeans(m1, specs="snail")
m2_emm <- emmeans(m2, specs="snail")
m1_marginal <- contrast(m1_emm, method="revpairwise", adjust="none")
m2_marginal <- contrast(m2_emm, method="revpairwise", adjust="none")

con3 <- list(snail=contr.sum, crab=contr.sum)
m3 <- lm(algae ~ snail*crab, data=fake_data_missing, contrasts=con3)
m4 <- lm(algae ~ snail + crab, data=fake_data_missing, contrasts=con3)
m3_coef <- coef(summary(m3))
m4_coef <- coef(summary(m4))
m3_anova <- Anova(m3, type="3")
m4_anova <- Anova(m4, type="3")
m4_anova_2 <- Anova(m4, type="2")
m2_anova_2 <- Anova(m2, type="2")
m3_anova_2 <- Anova(m3, type="2")

(res_table <- data.table(" "=c("Estimate", "SE", "df", "statistic", "p-value"),
  marginal_full=unlist(summary(m1_marginal)[1, c(2:6)]),
  anova_full=c(NA, NA, round(m3_anova["Residuals", "Df"],0), unlist(m3_anova[2, 3:4])),
  marginal_add=unlist(summary(m2_marginal)[1, c(2:6)]),
  anova_add=c(NA, NA, round(m4_anova["Residuals", "Df"],0), unlist(m4_anova[2, 3:4])))
)

(type_2_table <- data.table(" "=c("Estimate", "SE", "df", "statistic", "p-value"),
  marginal_add=unlist(summary(m2_marginal)[1, c(2:6)]),
  T2_add.dc=c(NA, NA, round(m2_anova_2["Residuals", "Df"],0), unlist(m2_anova_2[1, 3:4])),
  T2_add.ec=c(NA, NA, round(m4_anova_2["Residuals", "Df"],0), unlist(m4_anova_2[1, 3:4])),
  T3_add.ec=c(NA, NA, round(m4_anova["Residuals", "Df"],0), unlist(m4_anova[2, 3:4])),
  T2_full.ec=c(NA, NA, round(m3_anova_2["Residuals", "Df"],0), unlist(m3_anova_2[1, 3:4])))
)
```

# heterogeneity
